### ISSUE TITLE
JavaScript (Web Worker)  vs javascript ES6 (xjavascript)

### ISSUE THREAD

**Issue by MRYingLEE** [DerThorsten/xeus-javascript#7]
In your demo, both JavaScript (Web Worker) and javascript ES6 (xjavascript) are provided. Obviously, xjavascript is much better.
I am wondering whether the improvement comes from architecture, such as xeus, or only from implementation. In other words, can JavaScript (Web Worker) be improved to follow the xjavascript?
We are actually trying to improve JavaScript (Web Worker). So it is a big question for us to continue or not. It seems xjavascript can meet our requirement, but JavaScript (Web Worker) is a much lighter solution.
Please clarify. 
Thanks.

**Comment by DerThorsten** [comment]
Most nice things of xjavascript can easy be ported to the webworker javascript demo (xjavascript also runs also in a webworker FYI).
Most things could also just be copy fasted from xjavascript.

**Comment by jtpio** [comment]
> but JavaScript (Web Worker) is a much lighter solution.

Maybe there is room to improve the size of the `xeus-javascript`?

Also the original JavaScript kernel in JupyterLite was mostly developed for demo purposes, and also because JavaScript runs in the browser by default. But if `xeus-javascript` has more features and capabilities it can make sense to just focus effort on developing `xeus-javascript`, and deprecate the original JavaScript kernel (or move it to a separate repo so folks could fork it if they want to).
